schema_version: 2
id: 830d1d02-0479-4cf6-b61d-d115c1d7d6bc
title: Field CTO EMEA
company: unframe
company_url: null
location: Amsterdam, North Holland, Netherlands; Berlin, Berlin, Brussels-Capital,
  Stockholm, Sweden
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: field-cto-emea-amsterdam-north-holland-netherlands-berlin-berlin-brussels-capital-stockholm-sweden-197015
  url: https://www.arbeitnow.com/jobs/companies/unframe/field-cto-emea-amsterdam-north-holland-netherlands-berlin-berlin-brussels-capital-stockholm-sweden-197015
  metadata:
    tags:
    - Product
published_at: '2026-07-26T18:16:10Z'
discovered_at: '2026-07-26T21:18:48Z'
updated_at: '2026-07-28T21:31:57Z'
status: rejected
status_history:
- status: found
  changed_at: '2026-07-26T21:18:48Z'
- status: rejected
  changed_at: '2026-07-28T21:31:57Z'
analysis_priority: 0
fingerprint: sha256:ff7b4b40ccf5a2cc8a9bff127c0cddf79a686a701143cc8a628c0af2f85d2e2d
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
