schema_version: 2
id: 845ed571-ba52-400c-b326-3cbe258665ba
title: Senior Consultant (m/f/d) Data & AI Strategy
company: Artefact
company_url: null
location: Berlin, Berlin; München, Bavaria
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: senior-consultant-data-ai-strategy-berlin-berlin-munchen-bavaria-204514
  url: https://www.arbeitnow.com/jobs/companies/artefact/senior-consultant-data-ai-strategy-berlin-berlin-munchen-bavaria-204514
  metadata:
    tags:
    - Consulting & Data
published_at: '2026-08-03T20:56:02Z'
discovered_at: '2026-08-03T22:03:23Z'
updated_at: '2026-08-04T00:30:01Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-03T22:03:23Z'
analysis_priority: 0
fingerprint: sha256:cfa9844e5ce4cd2ea107f0d1e6897918be5172584d97c38f911a106a079ff154
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
