schema_version: 2
id: f119b4a0-90e5-47f1-b9f8-ed4577eb313c
title: Leitung Finanzbuchhaltung & Controlling (m/w/d) in Vollzeit
company: Gallus Druckmaschinen GmbH
company_url: null
location: Langgöns
remote: false
employment_type: berufserfahren
sources:
- source: arbeitnow
  source_job_id: leitung-finanzbuchhaltung-controlling-in-vollzeit-langgons-365391
  url: https://www.arbeitnow.com/jobs/companies/gallus-druckmaschinen-gmbh/leitung-finanzbuchhaltung-controlling-in-vollzeit-langgons-365391
  metadata:
    tags:
    - Controlling
    job_types:
    - berufserfahren
published_at: '2026-07-28T11:00:35Z'
discovered_at: '2026-07-28T12:37:10Z'
updated_at: '2026-07-28T15:47:36Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-28T12:37:10Z'
analysis_priority: 0
fingerprint: sha256:47e1c59d6eb120522c11db32d9d08d0d7d8581f7eba4a3c3d58ebb24159d771e
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
