schema_version: 2
id: 9ee195d9-d00b-48ef-980b-e3e131508d2d
title: Working Student Legal (all genders)
company: Q Energy
company_url: null
location: Berlin, Germany
remote: false
employment_type: Part time
sources:
- source: arbeitnow
  source_job_id: working-student-legal-all-genders-berlin-469680
  url: https://www.arbeitnow.com/jobs/companies/q-energy/working-student-legal-all-genders-berlin-469680
  metadata:
    tags:
    - Legal
    job_types:
    - Part time
published_at: '2026-08-01T05:20:27Z'
discovered_at: '2026-08-02T12:24:27Z'
updated_at: '2026-08-02T12:24:27Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-02T12:24:27Z'
analysis_priority: 0
fingerprint: sha256:2b7c90936c9e31647fd2b2dada4ff5e4605e5d80e6c3f5644b0128aa3ded04bb
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
