schema_version: 2
id: a1ef63a5-c246-4e05-bd03-cc910546d0f0
title: (Senior) Key Account Manager Italy (m/f/d)
company: Statista
company_url: null
location: Hamburg
remote: false
employment_type: Full Time
sources:
- source: arbeitnow
  source_job_id: senior-key-account-manager-italy-hamburg-418643
  url: https://www.arbeitnow.com/jobs/companies/statista/senior-key-account-manager-italy-hamburg-418643
  metadata:
    tags:
    - Revenue
    job_types:
    - Full Time
published_at: '2026-08-03T20:40:29Z'
discovered_at: '2026-08-03T22:04:27Z'
updated_at: '2026-08-03T22:04:27Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-03T22:04:27Z'
analysis_priority: 0
fingerprint: sha256:f8eeb69319e5637eb4a74faef6b6450be1dc54aa8a9a8a136a69c5bccb3d199c
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
