schema_version: 2
id: c6f41d3d-6718-4728-be5a-45ae9c47ff44
title: Trainee (m/w/d) Consulting
company: MLP Wirtschaftsberatung
company_url: null
location: Düsseldorf
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: trainee-consulting-dusseldorf-59696
  url: https://www.arbeitnow.com/jobs/companies/mlp-wirtschaftsberatung/trainee-consulting-dusseldorf-59696
  metadata:
    tags:
    - Finance
published_at: '2026-07-27T16:30:30Z'
discovered_at: '2026-07-27T18:02:53Z'
updated_at: '2026-07-28T09:55:14Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-27T18:02:53Z'
analysis_priority: 0
fingerprint: sha256:651a021c9a647567c2ed67ea11204808cb4248413261d3459999deff81861ab9
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
