schema_version: 2
id: 5f45dc5e-ce4b-4cbc-a130-bcc61bdc87fc
title: ISMS Experte (m/w/d)
company: hubside - Die Recruitingwerkstatt
company_url: null
location: Edling
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: isms-experte-edling-433807
  url: https://www.arbeitnow.com/jobs/companies/hubside-die-recruitingwerkstatt/isms-experte-edling-433807
  metadata:
    tags:
    - IT
published_at: '2026-07-24T09:00:32Z'
discovered_at: '2026-07-24T12:02:53Z'
updated_at: '2026-07-24T15:02:44Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-24T12:02:53Z'
fingerprint: sha256:aeb52b0637b88ff36687ca903f2948a32c95ad02d29def22bb82742410ba8aca
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
