schema_version: 2
id: e78e51a7-f142-40ab-9f77-53a8a297445a
title: Founding GTM Manager
company: Kuro Technology
company_url: null
location: Berlin
remote: false
employment_type: Full Time
sources:
- source: arbeitnow
  source_job_id: founding-gtm-manager-berlin-342913
  url: https://www.arbeitnow.com/jobs/companies/kuro-technology/founding-gtm-manager-berlin-342913
  metadata:
    tags:
    - Sales
    job_types:
    - Full Time
published_at: '2026-08-02T14:40:44Z'
discovered_at: '2026-08-02T16:01:51Z'
updated_at: '2026-08-02T17:05:05Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-02T16:01:51Z'
analysis_priority: 0
fingerprint: sha256:297ac563d3f3cebadbfc643efda4b7a31ed7071947b4dc5be21219e79d113d8c
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
