schema_version: 2
id: 209f8354-b7eb-423d-af7e-d55e183e9535
title: Staff Software Engineer, Product Engineering, EU
company: Ashby
company_url: null
location: Europe
remote: true
employment_type: null
sources:
- source: jobicy
  source_job_id: '142467'
  url: https://jobicy.com/jobs/142467-staff-software-engineer-product-engineering-eu
  metadata:
    company_logo: https://jobicy.com/data/server-nyc0409/galaxy/mercury/2025/08/63864ee6-221.png
    industry:
    - Software Engineering
    level: Senior
    excerpt: Hi I’m Abhik, Ashby's Co-Founder and VP of Engineering. We’re looking
      for an ambitious full-stack engineer who is laser-focused on solving customer
      problems and making the right long-term investments to solve them not only today
      but in our future features and products.What Ashby gives you in return is the
      best of both early and…
    salary:
      min: 141000
      max: 226000
      currency: EUR
      period: yearly
    discovered_by:
    - query_index: 1
      parameters:
        industry: dev
        geo: italy
        count: '100'
    - query_index: 2
      parameters:
        industry: dev
        geo: europe
        tag: backend
        count: '100'
    - query_index: 5
      parameters:
        industry: dev
        geo: emea
        tag: backend
        count: '100'
    - query_index: 7
      parameters:
        industry: dev
        geo: europe
        tag: technical lead
        count: '100'
    - query_index: 8
      parameters:
        industry: dev
        geo: europe
        tag: platform engineer
        count: '100'
published_at: '2026-07-26T10:10:08Z'
discovered_at: '2026-07-26T15:04:54Z'
updated_at: '2026-07-26T15:04:54Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-26T15:04:54Z'
analysis_priority: 0
fingerprint: sha256:402967cd074b9c368dd84cf7b34c5e9d7bdae7075a902bd39771ba14c65456a3
data_source: jobicy
content_source: jobicy
company_content_source: null
