schema_version: 2
id: 57cfe34f-5bc7-4eac-bb78-a7116294ea2a
title: Engineering Manager - Observability & Reliability Engineering Obsession (x/f/m)
company: Doctolib
company_url: null
location: Berlin
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: engineering-manager-observability-reliability-engineering-obsession-berlin-20715
  url: https://www.arbeitnow.com/jobs/companies/doctolib/engineering-manager-observability-reliability-engineering-obsession-berlin-20715
  metadata:
    tags:
    - Engineering
published_at: '2026-07-29T20:55:20Z'
discovered_at: '2026-07-29T21:19:07Z'
updated_at: '2026-07-29T21:19:07Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-29T21:19:07Z'
analysis_priority: 0
fingerprint: sha256:ea4f04bb7459b206a40706de24a57f58b4ac02c5e8fde2e46bf3fdae508f5df4
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
