schema_version: 2
id: c61bc180-021e-46a0-b75f-e99f7103ecf4
title: Wild Card
company: Zeit Ai
company_url: null
location: Munich
remote: false
employment_type: Full Time
sources:
- source: arbeitnow
  source_job_id: wild-card-munich-343005
  url: https://www.arbeitnow.com/jobs/companies/zeit-ai/wild-card-munich-343005
  metadata:
    tags:
    - Other
    job_types:
    - Full Time
published_at: '2026-08-04T11:40:28Z'
discovered_at: '2026-08-04T13:06:39Z'
updated_at: '2026-08-04T13:06:39Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-04T13:06:39Z'
analysis_priority: 0
fingerprint: sha256:8edc457b356c286a39fec0da1d350f67800b2928b476880bc7deb63190700707
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
