schema_version: 2
id: 317327e2-97a3-4aca-a21a-0364a3ca6222
title: Senior Backend Engineer - Databases - Loki Query | Germany | Remote
company: Grafana Labs
company_url: https://job-boards.greenhouse.io/grafanalabs
location: Germany (Remote)
remote: true
employment_type: null
sources:
- source: greenhouse
  source_job_id: '6123195004'
  url: https://job-boards.greenhouse.io/grafanalabs/jobs/6123195004
  metadata:
    board: grafanalabs
    internal_job_id: 5190897004
    requisition_id: '27157'
    updated_at: '2026-07-29T08:03:52-04:00'
    departments:
    - id: 4076488004
      name: 'R&D : Databases'
      child_ids: []
      parent_id: 4044019004
    offices:
    - id: 4087971004
      name: EMEA
      location: null
      child_ids:
      - 4088600004
      - 4088601004
      - 4088602004
      - 4087972004
      - 4087973004
      - 4087974004
      - 4087975004
      - 4087976004
      - 4087977004
      - 4087978004
      - 4087979004
      parent_id: null
    data_compliance:
    - type: gdpr
      requires_consent: false
      requires_processing_consent: false
      requires_retention_consent: false
      retention_period: null
      demographic_data_consent_applies: true
    ai_disclaimer: <p>We use Greenhouse's AI-powered Talent Match tool to compare
      your application against our job requirements.</p>
    ai_opt_out_request_url: http://app4.greenhouse.io/ai_opt_out_request/job_post/6123195004/ai_opt_out
published_at: '2026-07-23T12:08:21-04:00'
discovered_at: '2026-07-25T05:45:57Z'
updated_at: '2026-07-29T12:43:43Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-25T05:45:57Z'
analysis_priority: 0
fingerprint: sha256:ed4d1ca6ffce33fdcd6cea907c25cbd59b5a3ddd0d6c32ff595da225a979b600
data_source: greenhouse
content_source: greenhouse
company_content_source: null
