schema_version: 2
id: 7be23d7f-4304-4a02-9fc6-c1c2ac67185c
title: Software Engineer - Synthetic Monitoring | Sweden | Remote
company: Grafana Labs
company_url: https://job-boards.greenhouse.io/grafanalabs
location: Sweden (Remote)
remote: true
employment_type: null
sources:
- source: greenhouse
  source_job_id: '6130620004'
  url: https://job-boards.greenhouse.io/grafanalabs/jobs/6130620004
  metadata:
    board: grafanalabs
    internal_job_id: 5193652004
    requisition_id: '27166'
    updated_at: '2026-07-30T10:30:03-04:00'
    departments:
    - id: 4076488004
      name: 'R&D : Databases'
      child_ids: []
      parent_id: 4044019004
    offices:
    - id: 4087973004
      name: Germany (Remote)
      location: null
      child_ids: []
      parent_id: 4087971004
    - id: 4087979004
      name: Ireland (Remote)
      location: null
      child_ids: []
      parent_id: 4087971004
    - id: 4087978004
      name: Spain (Remote)
      location: null
      child_ids: []
      parent_id: 4087971004
    - id: 4087975004
      name: Sweden (Remote)
      location: null
      child_ids: []
      parent_id: 4087971004
    - id: 4087972004
      name: UK (Remote)
      location: null
      child_ids: []
      parent_id: 4087971004
    data_compliance:
    - type: gdpr
      requires_consent: false
      requires_processing_consent: false
      requires_retention_consent: false
      retention_period: null
      demographic_data_consent_applies: true
    ai_disclaimer: <p>We use Greenhouse's AI-powered Talent Match tool to compare
      your application against our job requirements.</p>
    ai_opt_out_request_url: http://app4.greenhouse.io/ai_opt_out_request/job_post/6130620004/ai_opt_out
published_at: '2026-07-30T10:30:03-04:00'
discovered_at: '2026-07-30T15:41:03Z'
updated_at: '2026-07-30T18:46:50Z'
status: rejected
status_history:
- status: found
  changed_at: '2026-07-30T15:41:03Z'
- status: rejected
  changed_at: '2026-07-30T18:46:50Z'
analysis_priority: 0
fingerprint: sha256:923d13dc66ad2f44548796cbfc1b7eabb6a783b2d527898fbc6a8508440429f3
data_source: greenhouse
content_source: greenhouse
company_content_source: null
