schema_version: 2
id: dea4f8ba-48c6-4e8a-8cc8-8aaf47705825
title: Software Developer (m/w/d)- Schwerpunkt Angular
company: isento GmbH
company_url: null
location: Nuremberg
remote: false
employment_type: berufserfahren
sources:
- source: arbeitnow
  source_job_id: software-developer-schwerpunkt-angular-nuremberg-110294
  url: https://www.arbeitnow.com/jobs/companies/isento-gmbh/software-developer-schwerpunkt-angular-nuremberg-110294
  metadata:
    tags:
    - Software Development
    job_types:
    - berufserfahren
published_at: '2026-07-27T07:00:29Z'
discovered_at: '2026-07-27T09:32:25Z'
updated_at: '2026-07-27T10:20:02Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-27T09:32:25Z'
analysis_priority: 0
fingerprint: sha256:bd764f3b1f9592d20987a3187dc06ffba775b48f956fd26455dfb7c109e2b42a
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
