schema_version: 2
id: 9c67d45d-bc95-4cbe-8d50-180b905869f8
title: Founding Product Manager - Berlin
company: Rootglobal
company_url: null
location: Berlin
remote: false
employment_type: Full Time
sources:
- source: arbeitnow
  source_job_id: founding-product-manager-berlin-161266
  url: https://www.arbeitnow.com/jobs/companies/rootglobal/founding-product-manager-berlin-161266
  metadata:
    tags:
    - Product & Design
    job_types:
    - Full Time
published_at: '2026-08-03T08:41:08Z'
discovered_at: '2026-08-03T13:04:32Z'
updated_at: '2026-08-03T13:04:32Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-03T13:04:32Z'
analysis_priority: 0
fingerprint: sha256:448725bc4d5a4902c1de3ed4987a2077a146117439aac4c5ae134980fec14169
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
