schema_version: 2
id: 5bd937a6-634f-4e7b-829b-d3cd01e53915
title: Staff / Senior Software Engineer (all genders)
company: Distribusion Technologies
company_url: null
location: Remote job
remote: true
employment_type: Experienced, fulltime permanent
sources:
- source: arbeitnow
  source_job_id: remote-staff-senior-software-engineer-all-genders-berlin-329891
  url: https://www.arbeitnow.com/jobs/companies/distribusion-technologies/remote-staff-senior-software-engineer-all-genders-berlin-329891
  metadata:
    tags:
    - Technology
    - Remote
    job_types:
    - Experienced
    - fulltime permanent
published_at: '2026-08-12T23:30:15Z'
discovered_at: '2026-08-13T06:29:39Z'
updated_at: '2026-08-13T06:29:39Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-13T06:29:39Z'
analysis_priority: 0
fingerprint: sha256:e29a54413dc4e68d11f458de778c32d16e80bbede3ed1c951c3c6d1ddf7574a4
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
