schema_version: 2
id: 86f361b2-6fc3-4dd9-9933-56be82e5c419
title: Senior Electrical Engineer - Robotics (m/f/d)
company: RobCo
company_url: null
location: Munich
remote: false
employment_type: Full Time
sources:
- source: arbeitnow
  source_job_id: senior-electrical-engineer-robotics-munich-419035
  url: https://www.arbeitnow.com/jobs/companies/robco/senior-electrical-engineer-robotics-munich-419035
  metadata:
    tags:
    - Engineering
    job_types:
    - Full Time
published_at: '2026-08-05T17:40:34Z'
discovered_at: '2026-08-05T19:01:14Z'
updated_at: '2026-08-06T03:01:56Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-05T19:01:14Z'
analysis_priority: 0
fingerprint: sha256:e003471b5aba421f154e4f87e5515924cca1c8739c867fde82a97eebd9dff39e
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
