schema_version: 2
id: 51fd0993-7a7b-497c-a630-80711052f613
title: SMB Account Executive, Germany
company: postman
company_url: null
location: Remote
remote: true
employment_type: null
sources:
- source: arbeitnow
  source_job_id: remote-smb-account-executive-germany-113713
  url: https://www.arbeitnow.com/jobs/companies/postman/remote-smb-account-executive-germany-113713
  metadata:
    tags:
    - Sales
published_at: '2026-07-30T03:16:29Z'
discovered_at: '2026-07-30T06:53:39Z'
updated_at: '2026-07-30T06:53:39Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-30T06:53:39Z'
analysis_priority: 0
fingerprint: sha256:997f1250a70fba428859371edbc8a42aa8e4faac0f828771f343b398b53f3e1f
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
