schema_version: 2
id: e4ca9a14-03df-442d-816e-27728b9fe953
title: 'Middle + / Senior Software Golang Kubernetes Engineer (Location: Portugal,
  Bulgaria, Croatia, Bosnia, Serbia, or Poland)'
company: Akvelon
company_url: https://jobs.dou.ua/companies/akvelon-ukraine/vacancies/
location: Гдиня (Польща), віддалено
remote: true
employment_type: null
sources:
- source: dou
  source_job_id: '370140'
  url: https://jobs.dou.ua/companies/akvelon-ukraine/vacancies/370140/
  metadata:
    discovered_by:
    - query_index: 2
      name: golang-remote
      url: https://jobs.dou.ua/vacancies/?remote&category=Golang
      category: Golang
    listing_date_label: 18 серпня
    listing_summary: Akvelon is an American company with offices in Seattle, Mexico,
      Ukraine, Poland, and Serbia. Our company is an official vendor of Microsoft
      and Google. Our clients also include Amazon, Evernote, Intel, HP, Reddit, Pinterest,
      AT&T, T-Mobile, Starbucks, and LinkedIn.
published_at: '2026-08-18'
discovered_at: '2026-08-18T12:08:05Z'
updated_at: '2026-08-18T12:08:05Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-18T12:08:05Z'
analysis_priority: 100
fingerprint: sha256:a8024ef3635904cfca7712608c0e99e98ee5d1f536192a9df481a8a0e7544706
data_source: dou
content_source: dou
company_content_source: dou
