schema_version: 2
id: eb683deb-05cc-45a1-854a-471d5c7a3f54
title: Working Student – Italian-speaking Data Researcher
company: Statista
company_url: null
location: Hamburg
remote: false
employment_type: Intern
sources:
- source: arbeitnow
  source_job_id: working-student-italian-speaking-data-researcher-hamburg-12833
  url: https://www.arbeitnow.com/jobs/companies/statista/working-student-italian-speaking-data-researcher-hamburg-12833
  metadata:
    tags:
    - Working students / Interns / Trainees
    job_types:
    - Intern
published_at: '2026-08-03T20:40:29Z'
discovered_at: '2026-08-03T22:03:43Z'
updated_at: '2026-08-03T22:03:43Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-03T22:03:43Z'
analysis_priority: 0
fingerprint: sha256:986fbd0bb5b75dbf0ab079ff42e950f2fef5c614d180616e80018d3d581f613e
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
