schema_version: 2
id: b5ec38da-0b31-49bf-b7ad-ca8c2c2647e7
title: Online Marketing Manager (Performance/Paid Media Specialist)
company: Aerogreet GmbH & CO KG
company_url: null
location: Frankfurt am Main
remote: false
employment_type: manager
sources:
- source: arbeitnow
  source_job_id: online-marketing-manager-performance-paid-media-specialist-frankfurt-am-main-491643
  url: https://www.arbeitnow.com/jobs/companies/aerogreet-gmbh-co-kg/online-marketing-manager-performance-paid-media-specialist-frankfurt-am-main-491643
  metadata:
    tags:
    - Marketing Manager
    job_types:
    - manager
published_at: '2026-07-31T15:30:26Z'
discovered_at: '2026-07-31T18:31:33Z'
updated_at: '2026-07-31T20:04:56Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-31T18:31:33Z'
analysis_priority: 0
fingerprint: sha256:62f900f4933f94a783965fc94814640775ec3d6d04dbc237a41f01eeaa885496
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
