schema_version: 2
id: a9d7821c-fa70-40aa-9655-941b2b42886a
title: Quality Engineer
company: Intuitive
company_url: null
location: Germany
remote: true
employment_type: null
sources:
- source: jobicy
  source_job_id: '143441'
  url: https://jobicy.com/jobs/143441-quality-engineer
  metadata:
    company_logo: https://jobicy.com/data/server-nyc0409/galaxy/mercury/2026/05/deceea09-221.png
    industry:
    - Software Engineering
    level: Senior
    excerpt: 'UnternehmensbeschreibungAt Intuitive, we are united behind our mission:
      we believe that minimally invasive care is life-enhancing care. Through ingenuity
      and intelligent technology, we expand the potential of physicians to heal without
      constraints.As a pioneer and leading company in the field of robotic-assisted
      surgery, we strive to foster an inclusive and diverse team, committed to making…'
    discovered_by:
    - query_index: 7
      parameters:
        industry: dev
        geo: europe
        tag: technical lead
        count: '100'
published_at: '2026-07-26T11:15:07Z'
discovered_at: '2026-07-26T15:05:39Z'
updated_at: '2026-07-28T21:31:57Z'
status: rejected
status_history:
- status: found
  changed_at: '2026-07-26T15:05:39Z'
- status: rejected
  changed_at: '2026-07-28T21:31:57Z'
analysis_priority: 0
fingerprint: sha256:ee0ec0057e369c217d5dd64554fc118448b5e16f040b2f9efcbd56612ee42759
data_source: jobicy
content_source: jobicy
company_content_source: null
