schema_version: 2
id: a688ae60-5f8f-4896-96ba-ff78dd15222f
title: 'Leiter Operations & Produktion (Site Director) | Region: Bodensee, Deutschland'
company: CONCAPE
company_url: null
location: Ravensburg
remote: false
employment_type: geschäftsleitung
sources:
- source: arbeitnow
  source_job_id: leiter-operations-produktion-site-director-region-bodensee-deutschland-ravensburg-264833
  url: https://www.arbeitnow.com/jobs/companies/concape/leiter-operations-produktion-site-director-region-bodensee-deutschland-ravensburg-264833
  metadata:
    tags:
    - Directors
    - Chief Executives
    job_types:
    - geschäftsleitung
published_at: '2026-07-24T15:30:44Z'
discovered_at: '2026-07-24T18:02:58Z'
updated_at: '2026-07-25T20:02:02Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-24T18:02:58Z'
analysis_priority: 0
fingerprint: sha256:7ecd39e8667f80c07883bf4f648aa38e4607604be63d54696e5b1891ec363b26
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
