schema_version: 2
id: 77c9c695-1bd4-482b-afd6-97eddaa5c347
title: Backend Engineer - Cards
company: sumup
company_url: null
location: Berlin
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: backend-engineer-cards-berlin-387430
  url: https://www.arbeitnow.com/jobs/companies/sumup/backend-engineer-cards-berlin-387430
  metadata:
    tags:
    - Backend
published_at: '2026-08-04T15:15:56Z'
discovered_at: '2026-08-04T17:03:44Z'
updated_at: '2026-08-04T17:03:44Z'
status: found
status_history:
- status: found
  changed_at: '2026-08-04T17:03:44Z'
analysis_priority: 0
fingerprint: sha256:59914de431323f7871b0b17c6b88fd6df498d906fa544bb85c3186087670c04c
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
