schema_version: 2
id: 8cf78e4b-7056-4b02-b1a5-6f4330d62478
title: Staff Infrastructure Software Engineer (Kubernetes)
company: cresta
company_url: null
location: null
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: staff-infrastructure-software-engineer-kubernetes-482719
  url: https://www.arbeitnow.com/jobs/companies/cresta/staff-infrastructure-software-engineer-kubernetes-482719
  metadata:
    tags:
    - Engineering
published_at: '2026-07-30T02:56:10Z'
discovered_at: '2026-07-30T04:01:20Z'
updated_at: '2026-07-30T06:53:43Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-30T04:01:20Z'
analysis_priority: 0
fingerprint: sha256:7e665fd31950e5646f26f5688a1ecb16fe834bb6fc53c96b7a02bc5188de1650
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
