from __future__ import annotations

import os
import uuid
from collections import Counter, defaultdict
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote

from .models import VACANCY_STATUSES
from .catalog_data import CatalogVacancy, load_catalog_vacancies

STATUSES = VACANCY_STATUSES
GENERATED_MARKER = "<!-- generated by job-intelligence; do not edit -->"
DEFAULT_MONTHLY_THRESHOLD = 100


class CatalogError(RuntimeError):
    pass


@dataclass(frozen=True, slots=True)
class CatalogResult:
    vacancies: int
    monthly: bool
    changed_files: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class VacancyRow:
    directory: Path
    vacancy: CatalogVacancy
    discovered_at: str
    status: str
    status_changed_at: str


def generate_catalog(
    registry_root: Path,
    catalog_root: Path,
    *,
    monthly_threshold: int = DEFAULT_MONTHLY_THRESHOLD,
) -> CatalogResult:
    if monthly_threshold < 1:
        raise ValueError("monthly_threshold must be positive")
    registry_root = registry_root.resolve()
    catalog_root = catalog_root.resolve()
    rows = _load_rows(registry_root)
    counts = Counter(row.status for row in rows)
    changed: list[str] = []
    expected_months: set[str] = set()

    if len(rows) > monthly_threshold:
        grouped: dict[str, list[VacancyRow]] = defaultdict(list)
        for row in rows:
            grouped[row.discovered_at[:7]].append(row)
        expected_months = set(grouped)
        for month in sorted(grouped, reverse=True):
            content = _monthly_catalog(month, grouped[month], catalog_root)
            path = catalog_root / f"{month}.md"
            if _write_atomic_if_changed(path, content):
                changed.append(path.name)
        index = _main_catalog(rows, counts, catalog_root, months=sorted(grouped, reverse=True))
        monthly = True
    else:
        index = _main_catalog(rows, counts, catalog_root)
        monthly = False

    index_path = catalog_root / "index.md"
    if _write_atomic_if_changed(index_path, index):
        changed.append(index_path.name)
    changed.extend(_remove_stale_months(catalog_root, expected_months))
    return CatalogResult(len(rows), monthly, tuple(sorted(changed)))


def _load_rows(registry_root: Path) -> list[VacancyRow]:
    rows = []
    for vacancy in load_catalog_vacancies(registry_root):
        rows.append(
            VacancyRow(
                vacancy.directory,
                vacancy,
                vacancy.discovered_at,
                vacancy.status,
                vacancy.status_changed_at,
            )
        )
    rows.sort(key=lambda row: (row.discovered_at, row.vacancy.vacancy_id), reverse=True)
    return rows


def _main_catalog(
    rows: list[VacancyRow],
    counts: Counter[str],
    catalog_root: Path,
    *,
    months: list[str] | None = None,
) -> str:
    lines = [GENERATED_MARKER, "", "# Vacancy Catalog", "", f"Total vacancies: {len(rows)}"]
    if rows:
        lines.append("")
        for status in STATUSES:
            if counts[status]:
                lines.append(f"- {_status_label(status)}: {counts[status]}")
    if months is not None:
        lines.extend(("", "## Monthly catalogs", ""))
        lines.extend(f"- [{month}]({month}.md)" for month in months)
        lines.extend(("", "## Recent vacancies", ""))
        lines.extend(_table(rows[:20], catalog_root))
    else:
        lines.extend(("", "## Vacancies", ""))
        lines.extend(_table(rows, catalog_root))
    return "\n".join(lines).rstrip() + "\n"


def _monthly_catalog(month: str, rows: list[VacancyRow], catalog_root: Path) -> str:
    lines = [
        GENERATED_MARKER,
        "",
        f"# Vacancy Catalog — {month}",
        "",
        "[Back to catalog](index.md)",
        "",
    ]
    lines.extend(_table(rows, catalog_root))
    return "\n".join(lines).rstrip() + "\n"


def _table(rows: Iterable[VacancyRow], catalog_root: Path) -> list[str]:
    lines = [
        "| Date | Company | Vacancy | Location | Source | Status | Changed | External | Company research | CV | Cover letter | Analysis | Interview |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        vacancy = row.vacancy
        directory_link = _relative_link(catalog_root, row.directory) + "/"
        job_link = _relative_link(catalog_root, Path(vacancy.artifacts.job_md or row.directory / "job.md"))
        company = f"[{_escape(vacancy.company)}]({directory_link})"
        title = f"[{_escape(vacancy.title)}]({job_link})"
        source_labels, external_links = _sources(vacancy.sources)
        lines.append(
            "| "
            + " | ".join(
                (
                    _escape(row.discovered_at[:10]),
                    company,
                    title,
                    _escape(vacancy.location),
                    source_labels,
                    _status_label(row.status),
                    _escape(row.status_changed_at[:10]),
                    external_links,
                    _optional_artifact_link(catalog_root, vacancy.artifacts.company_md, "Open"),
                    _artifact_pair(catalog_root, vacancy.artifacts.cv_md, vacancy.artifacts.cv_docx),
                    _artifact_pair(
                        catalog_root,
                        vacancy.artifacts.cover_letter_md,
                        vacancy.artifacts.cover_letter_docx,
                    ),
                    _optional_artifact_link(catalog_root, vacancy.artifacts.analysis_md, "Open"),
                    _optional_artifact_link(
                        catalog_root, vacancy.artifacts.interview_preparation_md, "Open"
                    ),
                )
            )
            + " |"
        )
    return lines


def _sources(value: Any) -> tuple[str, str]:
    labels = []
    links = []
    for item in value:
        if not isinstance(item, dict):
            continue
        source = str(item.get("source", "")).strip()
        label = source.replace("_", " ").title() or "Source"
        labels.append(_escape(label))
        url = str(item.get("url", "")).strip()
        if url:
            links.append(f"[{_escape(label)}]({_url(url)})")
    return ", ".join(labels) or "—", ", ".join(links) or "—"


def _artifact_pair(catalog_root: Path, markdown: str | None, docx: str | None) -> str:
    links = []
    for path, label in ((markdown, "MD"), (docx, "DOCX")):
        if path:
            links.append(f"[{label}]({_relative_link(catalog_root, Path(path))})")
    return " / ".join(links) or "—"


def _optional_artifact_link(catalog_root: Path, path: str | None, label: str) -> str:
    return f"[{label}]({_relative_link(catalog_root, Path(path))})" if path else "—"


def _relative_link(catalog_root: Path, path: Path) -> str:
    relative = os.path.relpath(path.resolve(), catalog_root.resolve()).replace("\\", "/")
    return quote(relative, safe="/._-")


def _status_label(value: str) -> str:
    return value.replace("_", " ").title()


def _escape(value: Any) -> str:
    return str(value or "—").replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def _url(value: str) -> str:
    return quote(value, safe=":/?#[]@!$&'*+,;-._~=%")


def _write_atomic_if_changed(path: Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        temp_path.write_text(content, encoding="utf-8", newline="\n")
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()
    return True


def _remove_stale_months(catalog_root: Path, expected: set[str]) -> list[str]:
    removed = []
    if not catalog_root.is_dir():
        return removed
    for path in catalog_root.glob("????-??.md"):
        if path.stem in expected:
            continue
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, IndexError):
            continue
        if first_line == GENERATED_MARKER:
            path.unlink()
            removed.append(path.name)
    return removed
