schema_version: 2
id: 4bbc490c-4d76-4567-ab3a-95299e656fde
title: Investment Analyst (m/w/d) im Bereich Kapitalmärkte
company: DeltaValue GmbH
company_url: null
location: Essen
remote: false
employment_type: null
sources:
- source: arbeitnow
  source_job_id: investment-analyst-im-bereich-kapitalmarkte-essen-51186
  url: https://www.arbeitnow.com/jobs/companies/deltavalue-gmbh/investment-analyst-im-bereich-kapitalmarkte-essen-51186
  metadata:
    tags:
    - Asset
    - Fonds Management
published_at: '2026-07-24T09:00:31Z'
discovered_at: '2026-07-24T12:02:54Z'
updated_at: '2026-07-24T12:02:54Z'
status: found
status_history:
- status: found
  changed_at: '2026-07-24T12:02:54Z'
fingerprint: sha256:b72a97ac4219ccfeabd78d4733b858383b8c8596be05f6d02449d14360532b31
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
