schema_version: 2
id: f152a84f-60cc-4187-9703-14d49011caf9
title: Senior Security Engineer - Remote
company: Parity
company_url: null
location: Remote
remote: true
employment_type: Contract
sources:
- source: arbeitnow
  source_job_id: senior-security-engineer-remote-359025
  url: https://www.arbeitnow.com/jobs/companies/parity/senior-security-engineer-remote-359025
  metadata:
    tags:
    - Acceleration
    job_types:
    - Contract
published_at: '2026-08-31T20:40:18Z'
discovered_at: '2026-09-01T06:12:20Z'
updated_at: '2026-09-01T06:12:20Z'
status: found
status_history:
- status: found
  changed_at: '2026-09-01T06:12:20Z'
analysis_priority: 0
fingerprint: sha256:704019b2490bd215b3a492cb12318a5e49f134cf4a1021b7dc4090166159cc7c
data_source: arbeitnow
content_source: arbeitnow
company_content_source: null
